### PR TITLE
Normative: Freeze the return object and array

### PR DESCRIPTION
**Pull request by FrankYFTang**
Address issue #62

### CODE REVIEW

**Comment by FrankYFTang** [comment]
@bathos

**Comment by bathos** [comment]
@FrankYFTang sorry I hadn’t caught the prior discussion. Freezing the objects makes sense to me. I may be missing something though because it appears orthogonal to issue #62, which was about preserving `Object.is(a.b, a.b) === true` semantics for intrinsic accessors. That will still be `false` with this change, right? Or is this “part 1” or something?

**Comment by FrankYFTang** [comment]
that is the problem I have. I really do not want to keep a copy of the object cached somewhere for the object because that will require the locale to increase at least a pointer to that. Maybe a better solution is just to change these getter to function?

**Comment by bathos** [comment]
> Maybe a better solution is just to change these getter to function?

That has the benefit of consistency with the direction that web platform APIs have been moving with things like this, favoring methods that return “plain” objects and arrays with each invocation. IIUC that shift has been motivated by the same interest in reducing the need for stateful bookkeeping without introducing confusing [[Get]] semantics.

**Comment by FrankYFTang** [comment]
Discuss this in the 2022-11-30 TC39 and many people prefer we move to change from getter to function. So I will close this PR and open a new one which change the getters to functions.

**Pull request closed without merging**
