### PR TITLE
Normative: Change the getters to methods

### PR DESCRIPTION
**Pull request by FrankYFTang**
Close #62

Per 2022-11-30 TC39 recommentations

### CODE REVIEW

**Comment by FrankYFTang** [comment]
@bathos  @rkirsling

**Comment by FrankYFTang** [comment]
@anba

**Comment by FrankYFTang** [comment]
We need to change the following test262 tests with this PR

  'intl402/Locale/prototype/calendars/branding': [FAIL],
  'intl402/Locale/prototype/calendars/name': [FAIL],
  'intl402/Locale/prototype/calendars/output-array': [FAIL],
  'intl402/Locale/prototype/calendars/prop-desc': [FAIL],
  'intl402/Locale/prototype/collations/branding': [FAIL],
  'intl402/Locale/prototype/collations/name': [FAIL],
  'intl402/Locale/prototype/collations/output-array': [FAIL],
  'intl402/Locale/prototype/collations/output-array-values': [FAIL],
  'intl402/Locale/prototype/collations/prop-desc': [FAIL],
  'intl402/Locale/prototype/hourCycles/branding': [FAIL],
  'intl402/Locale/prototype/hourCycles/name': [FAIL],
  'intl402/Locale/prototype/hourCycles/output-array': [FAIL],
  'intl402/Locale/prototype/hourCycles/output-array-values': [FAIL],
  'intl402/Locale/prototype/hourCycles/prop-desc': [FAIL],
  'intl402/Locale/prototype/numberingSystems/branding': [FAIL],
  'intl402/Locale/prototype/numberingSystems/name': [FAIL],
  'intl402/Locale/prototype/numberingSystems/output-array': [FAIL],
  'intl402/Locale/prototype/numberingSystems/prop-desc': [FAIL],
  'intl402/Locale/prototype/textInfo/branding': [FAIL],
  'intl402/Locale/prototype/textInfo/name': [FAIL],
  'intl402/Locale/prototype/textInfo/output-object': [FAIL],
  'intl402/Locale/prototype/textInfo/output-object-keys': [FAIL],
  'intl402/Locale/prototype/textInfo/prop-desc': [FAIL],
  'intl402/Locale/prototype/timeZones/branding': [FAIL],
  'intl402/Locale/prototype/timeZones/name': [FAIL],
  'intl402/Locale/prototype/timeZones/output-array': [FAIL],
  'intl402/Locale/prototype/timeZones/output-array-sorted': [FAIL],
  'intl402/Locale/prototype/timeZones/output-undefined': [FAIL],
  'intl402/Locale/prototype/timeZones/prop-desc': [FAIL],
  'intl402/Locale/prototype/weekInfo/branding': [FAIL],
  'intl402/Locale/prototype/weekInfo/name': [FAIL],
  'intl402/Locale/prototype/weekInfo/output-object': [FAIL],
  'intl402/Locale/prototype/weekInfo/output-object-keys': [FAIL],
  'intl402/Locale/prototype/weekInfo/prop-desc': [FAIL],

**Review by gibson042 — APPROVED** [review]

**Comment by FrankYFTang** [comment]
https://github.com/tc39/test262/issues/3746

**Comment by gibson042** [comment]
My approval stands, but I would also like to see the names of properties that users must invoke as functions indicate that fact with a "get" prefix, especially since [Locale instances already have non-function properties](https://tc39.es/ecma402/#sec-properties-of-intl-locale-prototype-object).
* `calendars` → `getCalendars`
* `collations` → `getCollations`
* `hourCycles` → `getHourCycles`
* `numberingSystems` → `getNumberingSystems`
* `timeZones` → `getTimeZones`
* `textInfo` → `getTextInfo`
* `weekInfo` → `getWeekInfo`

**Comment by sffc** [comment]
TG2 discussion: https://github.com/tc39/ecma402/blob/master/meetings/notes-2022-12-08.md#normative-change-the-getters-to-methods-65

Conclusion: We are not clear on whether the functions should have a `get` prefix, like `getTextInfo()` or `getCollations()` versus `textInto()` or `collations()`. We would like to appeal for further discussion.

CC @zbraniecki @bakkot @michaelficarra @waldemarhorwat @ljharb @ptomato

**Comment by bathos** [comment]
Soft preference for the `get` prefix because I find it adds considerable clarity when reading.

(Arguing against myself here, but:) because Intl already omits it for the `Intl.<constructor>.prototype.resolvedOptions` methods and Web platform API norms seem to be converging on omission of `get`, too (e.g. `HTMLSlotElement.prototype.assignedNodes`), a consistency argument could favor omission. The `Date.prototype.getFoo` methods seem more like pre-accessor oddballs to me than a strong precedent — they return primitives and each has a corresponding setFoo, and this pattern would be weird in a new API unless additional arguments are needed or could make sense (e.g. `DataView`).

**Comment by gibson042** [comment]
> Soft preference for the `get` prefix because I find it adds considerable clarity when reading and likely aids discovery & conveys the expected usage pattern. You don’t need to look up whether or not `getCalendars` is a method.

Exactly (elaborated further above).

> That particular pattern would be weird in a new API except when additional arguments are needed or could make sense (e.g. `DataView`).

Or when some properties are data getters while others must be invoked as methods, which is the case here. It's true that Maps and Sets already have that mix with a non-method `size`, but a) it's much easier to remember a single-property exception than a big jumble of both kinds, and b) even so, that kind of confusion _does_ exist—people (including me) really do write `map.size()` before realizing their mistake, and we should strive to limit such friction.

**Comment by zbraniecki** [comment]
My position is soft rejection of `get` prefix - new APIs such as `Map` and `Set` do not use `get*` in cases such as `Map::keys()`, `Map::entries()`, `Map::values()` and I enjoy [Rust code convention](https://rust-lang.github.io/api-guidelines/naming.html#getter-names-follow-rust-convention-c-getter) discouraging from use of `get` for getters.

**Comment by ljharb** [comment]
Those are all actual getters - methods that get are nice with the “get” prefix, since they’re a verb, which indicates function-ness.

**Comment by ljharb** [comment]
@zbraniecki ”actual getters” are seemingly normal properties that magically/implicitly call a function - as such, it’s appropriate to name them as if they were properties. Things that look like functions should generally be named with a verb, since they *do* things - and in this case, the thing the methods do is “get” something.

**Comment by zbraniecki** [comment]
Thanks, I'm still a bit confused about your position here.

> ”actual getters” are seemingly normal properties that magically/implicitly call a function - as such, it’s appropriate to name them as if they were properties. Things that look like functions should generally be named with a verb, since they do things - and in this case, the thing the methods do is “get” something.

`keys` is "actual getter" according to that logic, or "thing that looks like function"? What about "entries", "values", "collations", "calendars", "timeZones"?

Which ones, in your opinion, are "actual getters" and which ones are "things that look like functions"?

**Comment by zbraniecki** [comment]
> When i say “actual” I’m referring to whether it’s an accessor property vs a function-valued data property.

Can you classify using your mental model the following:

* `Map::keys`,
* `Map::entries`,
* `Map::values`,
* `LocaleInfo::collations`,
* `LocaleInfo::calendars`,
* `LocaleInfo::timeZones`

?

**Comment by ljharb** [comment]
I'm not familiar with the LocaleInfo ones, but yes, Map/Array/Set keys/entries/values are methods, but poorly named imo since they aren't verbs - they're named more like accessors (but their semantics aren't appropriate for accessors, since they return a new object every time). I don't want to repeat that pattern elsewhere if we can avoid it.

**Comment by zbraniecki** [comment]
Thanks, so I derive from your words that your position is that `Map::entries()` should be `Map::getEntries()` etc. And therefore analogous methods on `LocaleInfo` should also use `get*`.

> I don't want to repeat that pattern elsewhere if we can avoid it.

Do you feel this position is universally accepted in TC39, is the group split, or do you think your opinion is in minority?

**Comment by ljharb** [comment]
Yep, that sounds accurate.

I don't think this kind of naming question has come up before such that I have any idea what the group thinks - the naming of Object.values/entries was precedented by Object.keys, and nothing similar that I can recall has been added since ES6 (ie, with the modern process).

**Comment by bathos** [comment]
In addition to aligning with the static Object methods (for which “methodness” is relatively unambiguous), the keys/entries/values trio constitutes an informal generic iterable collection contract shared by Array, Map and Set. On the web platform, these are joined by each interface that uses iterable, maplike, and setlike declarations, too. That impacts the calculus a bit imo. There’s nothing similarly generic about concepts like “the calendars of something”.

**Comment by bathos** [comment]
> But I'm struggling a mental model that says "if a method is to be shared between a range of types, then it shouldn't use the prefix, but if it's just for one type, it should".

I agree — like ljharb had said, these examples had a particular “lineage”. I meant more that they happened to be less problematic.

> My position is the one derived from Rust code convention - getters shouldn't use get :) And I think I'm quite universal about it.

Mine comes from JS + JS APIs on the web platform, where getters (in the sense of accessor property [[Get]] functions) are typically nouns and methods typically include verbs if they appear on meaningfully stateful objects. But there are enough exceptions that I couldn’t claim this is universal or anything.

**Comment by bathos** [comment]
> How can you predict that? It's quite common in my experience that you start with a getter and only later extend the API to have a setter. If at the time of deciding on the getter you don't know if you'll ever need a setter (this is the case here - we don't think we'll need setters, but maybe in a couple years someone will propose one?) then as API designer you're forced to see the future.

I think this is why they’re almost always either real getters or, if something prevents that like here, methods that use `getX` naming? FWIW, in the web platform in particular, this sort of naming issue just doesn’t seem to show up much in the first place because actual getters outnumber “get methods” by at least an order of magnitude.

**Comment by gibson042** [comment]
Even if there were general guidance against a "get" prefix, I would still argue for having it here to improve the developer experience by more clearly differentiating which properties of a Locale instance must be invoked as methods.

**Comment by FrankYFTang** [comment]
here is what I will do. I will keep this PR unchanged with the current name, but I will open another PR which have the name changed. So we will have two PR side by side and we will talk about in TC39 and I assume one of that will be picked (I assume the new one will be) . How about that?

**Comment by FrankYFTang** [comment]
Another PR with also the name changes in https://github.com/tc39/proposal-intl-locale-info/pull/67

**Comment by FrankYFTang** [comment]
In 2023-01-31 TC39 meeting the concensus is merge PR 67 but not PR65

**Pull request closed without merging**
